baseURL = "http://example.com/"
languageCode = "en-us"
title = "Paperesque theme example"
theme = "paperesque"
copyright = "© 2011-2020 Fabian Tamp"

# I can't remember if this is required for syntax highlighting or not.
pygmentsUseClasses = true

# Uncomment these lines for droplist / resource removal support! See the
# README for more details

# [outputs]
# page = ["HTML", "droplist"]

[params]
# Turn this on if you want to disable margin notes everywhere!
# disableMarginNotes = true

# Customise your home page menu here:

[[params.menu]]
  name = "Recent Posts"
  url = "posts/"

[[params.menu]]
  name = "Posts by Tag"
  url = "tags/"

[[params.menu]]
  name = "About the contents of this example site"
  url = "about/"

[[params.menu]]
  name = "Link to theme on Github"
  url = "https://github.com/capnfabs/paperesque"


# And your top-right menu links here.

[[params.topmenu]]
  name = "my favourite bird"
  url = "posts/kookaburra"

[[params.topmenu]]
  name = "rss"
  url = "posts/index.xml"
